name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Run tests
        run: cargo test
      - name: Build release
        run: cargo build --release
      - name: Upload artifact (Unix)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: ldactl-${{ runner.os }}
          path: target/release/ldactl
      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: ldactl-${{ runner.os }}
          path: target/release/ldactl.exe
